spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:chequer-interview
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
