INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');
INSERT INTO user (email) VALUES ('test@email.com');

insert into workspace (id, name, owner_id) values (null, 'test workspace', 10);
insert into workspace_member (id, member_id, workspace_id) values (null, 11, 1);
insert into workspace_member (id, member_id, workspace_id) values (null, 12, 1);
insert into workspace_member (id, member_id, workspace_id) values (null, 13, 1);
insert into workspace_member (id, member_id, workspace_id) values (null, 14, 1);
insert into workspace_member (id, member_id, workspace_id) values (null, 15, 1);
insert into workspace_member (id, member_id, workspace_id) values (null, 16, 1);
insert into workspace_member (id, member_id, workspace_id) values (null, 17, 1);
insert into workspace_member (id, member_id, workspace_id) values (null, 18, 1);
insert into workspace_member (id, member_id, workspace_id) values (null, 19, 1);
insert into workspace_member (id, member_id, workspace_id) values (null, 20, 1);
